services:
  - type: static
    name: quickbook
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - path: /assets/*
        dest: /assets/$1
      - path: /*
        dest: /index.html
